### ISSUE TITLE
[debian] [stretch] gzip default should be on not off

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack-formulas/nginx-formula#180]
When deploying nginx formula to debian stretch with no pillars, it switches gzip from on to off... Is this intentional ? Can we switch to on by default ?

**Comment by EvaSDK** [comment]
gzip should probably remain to off due to https://en.wikipedia.org/wiki/BREACH

Also, looking at other tickets you just opened, please consider the defaults should probably not be tied to a specific distribution. It would also increase maintenance burden for the formula while you as an administrator, you most likely know what's best for your platform.
Imho, and considering the debate from the POV of other formulas providing internet facing services, formulas should either stick to upstream default settings (easiest) or try to provide the most secure default settings.

**Comment by EvaSDK** [comment]
Additional point, modern front-end should provide pre-compressed static files to workaround the aforementioned potential security issue. Nginx can then be configured to use `gzip_static` which transparently sends the appropriate files according the request headers.

**Comment by noelmcloughlin** [comment]
Question was answered.
