### ISSUE TITLE
[BUG] Run fails if nginx.server.snippets is not defined in pillar

### ISSUE THREAD

**Issue by hkbakke** [saltstack-formulas/nginx-formula#274]
If nginx.server.snippets is not defined in my pillar file, the run fails. Just adding ```{}``` as value is enough to work around the problem.

The issue seems to be occuring at the pop in nginx/snippets.sls.

Currently using https://github.com/saltstack-formulas/nginx-formula/commit/19203409aeb40b042cffb0e4d39bc66303f17842

**Comment by anderbubble** [comment]
I looked at this a bit. First I expected the best way to fix it would be to add a default value to `_nginx.pop('snippets')`[1] (something like `_nginx.pop('snippets', {})`). But there are other uses of `.pop()` in the formula and none of them are specifying a default value.

So I started asking myself why `snippets.sls` is being loaded at all. Sure enough, it looks to me like it shouldn't be if `snippets` isn't defined in Pillar.[2]

So I think the real bug is in the fact that `nginx.snippets is defined` is returning `True` even when `snippets` is not in Pillar.

[1]: https://github.com/saltstack-formulas/nginx-formula/blob/master/nginx/snippets.sls#L11

[2]: https://github.com/saltstack-formulas/nginx-formula/blob/master/nginx/init.sls#L13-L15

**Comment by Yoda-BZH** [comment]
Hello,

Any update ? The PR fixes the problem for me.

**Comment by myii** [comment]
> Hello,
> 
> Any update ? The PR fixes the problem for me.

@Yoda-BZH It seems that @javierbertoli is [waiting for the final adjustments](https://github.com/saltstack-formulas/nginx-formula/pull/275#issuecomment-823514825):

> @anderbubble wonderful! I'll wait for your changes to merge this.

**Comment by Yoda-BZH** [comment]
ho, ok thanks :)

**Comment by myii** [comment]
> Hello,
> 
> Any update ? The PR fixes the problem for me.

@Yoda-BZH So #275 has been merged but with a minor adjustment.  Can you confirm that it is still working for you?
