### ISSUE TITLE
Creating vhosts should be an importable macro

### ISSUE THREAD

**Issue by dferrantelli** [saltstack-formulas/nginx-formula#81]
That way if you are working to make a formula to manage monit or other applications, the vhosts for these applications can be created from that formula. That way something like this could be used:

``` yaml
{% from 'monit/map.sls' import monit with context %}
{% from 'nginx/ng/vhosts_config.sls' import vhost_create with context %}

{% for app in {{ monit.apps.items() }} %}
{{ vhost_create('app') }}
{% endfor %}
```

This would assume of course that all the necessary config aspects are in the monit.apps map.

**Comment by edvinasme** [comment]
+1

**Comment by noelmcloughlin** [comment]
I had a look at this feature request - I understand the motivation - its not simple and technically not required or desirable depending on your opinion about 1-1 coupling v.s. shared libraries.

**To do this.**
1. The vhost SLS file is now called `config_servers.sls`
2. Monit must import all macros _(preferably from a macros.jinja  file)_
```
{% from 'nginx/ng/servers_config.sls' import path_join, disabled_name, server_path, server_curpath, manage_status, with context %}
```
3. monit must import all mappings (they use the `nginx` dict.)
```
{% from "nginx/ng/map.jinja" import nginx with context %}
```
4. TIntroduces direct dependency between two code bases.


**Alternative solution (indirect dependency)**

1. Include the `nginx.ng` alongside monit formula.
```
base:
  '*':
    - apache.uninstall
    - nginx.ng
    - monit
```
2. Declare monit application vhosts under nginx.ng pillar data.
```
nginx:
  ng:
     ... bla ...

monit:
   ... bla ...
```

**Conclusion**
I will close this issue - its four years old.
Nobody ever contributed the feature.  
The `vhosts_config.sls` filename went away in 2016. 
This issue is stale.
